server:
  port: 9527

spring:
  application:
    name: cloudbest-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.200:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true  #微服务名称以小写形式呈现
      routes:
        - id: cloudbest_routh1   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloudbest-provider-service #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/**         # 断言，路径相匹配的进行路由

        - id: cloudbest_routh2
          uri: lb://cloudbest-consumer-service
          predicates:
            - Path=/consumer/**











