#配置到nacos配置中心动态获取刷新
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true  #微服务名称以小写形式呈现
      routes:
        - id: cloudbest_routh1 #payment_route    #路由的ID,没有固定规则,名字可以随便取但要求唯一
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloudbest-consumer-service #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/**         # 断言，路径相匹配的进行路由

        - id: cloudbest_routh2 #payment_route    #路由的ID,没有固定规则,名字可以随便取但要求唯一
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloudbest-provider-service #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/**         # 断言，路径相匹配的进行路由